### ISSUE TITLE
Line 86

### ISSUE THREAD

**Issue by Wojtala** [mtahle/diy-wrc#1]
Dear Mujahed1987,
Thank you for this code. I am trying to used for a slightly different application which is RC Plane. 
I am new to the coding and Arduino but when I am trying to compile your original code in my computer the compiler returns with such an error in line 86:

Rx_Baord_2_0.ino: In function 'void loop()':
Rx_Baord_2_0:86: error: void value not ignored as it ought to be

I tried many different combinations but it always appear here. 

Would you mind to have a look in the code again and see if there is any solution to that? 

Thank you very much in advance,
Yours,
Wojtek

**Comment by mtahle** [comment]
Thank you for the feedback, please give me couple of days to solve the issue since I am too busy now
Regards.
Mujahed

**Comment by mtahle** [comment]
Hello Wojtala

Please provide me with you complete code
